version: '3'
services:
  users:
    build: users/
    ports:
      - "3001:5001"
    environment:
      - PORT=5001
      - ConnectionStrings__DefaultConnection=Username=userapp;Password=abc123;Host=postgres;Port=5432;Database=chat;Pooling=true;
    depends_on:
      - redis
      - postgres
  redis:
    build: redis/
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=userapp
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_DB=chat
    ports:
      - '5432:5432'