version: '3'
services:
  # users:
  #   build: users/
  #   ports:
  #     - "3001:5001"
  #   environment:
  #     - PORT=5001
  #     - ConnectionStrings__DefaultConnection=Username=userapp;Password=abc123;Host=postgres;Port=5432;Database=chat;Pooling=true;
  #   depends_on:
  #     - "postgres"
  # redis:
  #   build: redis/
  #   ports:
  #     - "6379:6379"
  users_node:
    build: users_node/
    ports:
      - "3002:80"
    environment:
      - DB_HOST=postgres
      - DB_USER=userapp
      - DB_NAME=chat
      - DB_PASSWORD=abc123
    depends_on:
    # https://docs.docker.com/compose/startup-order/
      - postgres
    command: ["./postgres/wait.sh", "postgres", "node", "./users_node/index.js"]
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=userapp
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_DB=chat
    ports:
      - '5432:5432'