version: '3'
services:
  users:
    build: users/
    ports:
      - "3001:5001"
    # @TODO: Pass configuration files through to appsettings / find best practice for this
    environment:
      - ASPNETCORE_PORT=5001
    depends_on:
      - redis
  redis:
    build: redis/
    ports:
      - "6379:6379"