version: '3'
services:
  users:
    build: src/services/users/
    ports:
      - "3001:5001"
    environment:
      - PORT=5001
      - ConnectionStrings__DefaultConnection=Username=userapp;Password=abc123;Host=postgres;Port=5432;Database=chat;Pooling=true;
      - EventBusConfig__HOST=rabbit
      - EventBusConfig__USER=user
      - EventBusConfig__PASSWORD=abc123
    depends_on:
      - "postgres"
      - "rabbit"
  # redis:
  #   build: src/components/redis/
  #   ports:
  #     - "6379:6379"
  rabbit:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=abc123
    ports:
      - "15672:15672"
      - "5672:5672"
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=userapp
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_DB=chat
    ports:
      - '5432:5432'